# Generated by Django 5.2.1 on 2025-05-14 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_formulario_agente_ciudadano_opcion_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='ciudadano',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Ciudadano', 'verbose_name_plural': 'Ciudadanos'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['nombre'], 'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={'ordering': ['orden'], 'verbose_name': 'Opción', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='tipificacion',
            options={'ordering': ['opcion__orden'], 'verbose_name': 'Tipificación', 'verbose_name_plural': 'Tipificaciones'},
        ),
        migrations.RemoveIndex(
            model_name='evaluacion',
            name='usuarios_ev_numero__ecefc9_idx',
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='tipificacion',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='tipificacion',
            old_name='descripcion',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='nombre_ciudadano',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='numero_identificacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='tipo_identificacion',
        ),
        migrations.AddField(
            model_name='agente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('C', 'Completada'), ('A', 'Archivada')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.formulario'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opcion',
            name='requiere_observacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipificacion',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipificaciones', to='usuarios.evaluacion'),
        ),
        migrations.AddField(
            model_name='tipificacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tipificacion',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.opcion'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='usuarios.agente'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='usuarios.ciudadano'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='id_conversacion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['id_conversacion'], name='usuarios_ev_id_conv_b80367_idx'),
        ),
        migrations.RemoveField(
            model_name='tipificacion',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='tipificacion',
            name='cedula',
        ),
    ]
