# Generated by Django 5.2.1 on 2025-05-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_agente_options_alter_ciudadano_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipificacion',
            unique_together={('evaluacion', 'opcion')},
        ),
    ]
